### ISSUE TITLE
Option to "quick add to Inbox"

### ISSUE THREAD

**Issue by sotakal** [HipsterBrown/send-to-todoist#8]
I like how the new Outlook/O365 Todoist addon works - could we get a similar "quick add" option, that would immediately create a new task with no due date in Inbox?
![image](https://user-images.githubusercontent.com/64089225/115428468-b7125b80-a202-11eb-82db-1a41f56228d9.png)

I see three alternative ways how this could work, all with their pros and cons:
![td](https://user-images.githubusercontent.com/64089225/115427580-df4d8a80-a201-11eb-97fa-ee4528868ba2.png)

**Option A**
(+) Small change compared to current state
(+) No need to relearn muscle memory of using previously available hotkeys
(-) There are two almost identical options right next to each other
(-) The 0 hotkey is on the very right of the keyboard

**Option B**
(+) More compact option for people with long project list (I have almost 20, for example and with the new Proton redesign the context menu is huge) 
(-) Longer time to save to a specific project (on the other hand inbox is much faster, as dropdown is always super compact with only 2 items and right below the mouse cursor)

**Option C** 
(+) Could be very lightweight or advanced, according to preference
(+) The extension could a direct lightweight competitor to the official Todoist extension
(-) You can only use one mode at one time
(-) There would have to be a new setting in the extension configuration

My personal preferences would be B > C >A but any of these I would welcome for situations when I need quick Inbox access.

**Comment by HipsterBrown** [comment]
@sotakal  I wasn't sure how to share this new feature in the recent releases, other than adding it to the addon description:

> To quickly add a page as a task in your Inbox, use the keyboard shortcut: Cmd+Shift+I (Ctrl+Shift+I on Linux and Windows)
https://addons.mozilla.org/en-US/firefox/addon/send-to-todoist/

But that only works for pages, not links or highlighted text, so this feature proposal would help. Thanks for the clear breakdown of options. :clap:

**Comment by sotakal** [comment]
Oh, that's a great! The only downside is that Ctrl+Shift+I on Windows opens the Firefox Web Developer Tools (see [the documentation](https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts)), so a customizable hotkey would be nice.

**Comment by HipsterBrown** [comment]
This feature has been shipped with version 1.9.0 of the extension. You can see it in the updated screenshot in the README and on the addon page. I ended up using option A as the quickest implementation without completely refactoring the menu system, with the caveat of using `S` (for "Send to Inbox") as the hotkey instead of `0`.

I'm going to work on a larger refactor of the extension to move the API key setting to an options page and (maybe) allow for configuration of the menus system based on the options you described here. An options page would provide enough space for some time of onboarding experience and more advanced feature configuration.

**Comment by sotakal** [comment]
Works a treat, thanks so much! 👌
